name: Build

# trigger on tags
on:
  push:
    tags:
      - "*"

# an undocumented permissions thing required for AWS Credentials
permissions:
  id-token: write
  contents: read

# for windows and linux
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            artifact: opencv-linux-${{ github.ref_name }}.tar.zst
          - os: windows-2019
            artifact: opencv-win64-${{ github.ref_name }}.7z

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add MSBuild to PATH
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.1

      - name: Free disk space
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build Linux artifact
        if: contains(matrix.os, 'ubuntu')
        working-directory: ${{ github.workspace }}
        run: scripts/build.sh ${{ matrix.artifact }}

      - name: Build Windows artifact
        if: contains(matrix.os, 'windows')
        working-directory: ${{ github.workspace }}
        run: scripts/build.ps1 ${{ matrix.artifact }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.aws_iam_role }}
          aws-region: ap-northeast-1

      - name: Upload artifact
        working-directory: ${{ github.workspace }}
        run: |
          aws s3 cp ${{ matrix.artifact }} ${{ secrets.aws_s3_bucket }}

