name: Build

# trigger on tags
on:
  push:
    tags:
      - "*"

# an undocumented permissions thing required for AWS Credentials
permissions:
  id-token: write
  contents: read

# for windows and linux
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            artifact: opencv-linux-${{ github.ref_name }}.tar.zst
            command: scripts/build.sh
          - os: windows-2019
            artifact: opencv-win64-${{ github.ref_name }}.7z
            command: scripts/build.ps1

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Add MSBuild to PATH
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.1

      - name: Maximize build space
        uses: easimon/maximize-build-space@master

      - name: Build artifact
        working-directory: ${{ github.workspace }}
        run: ${{ matrix.command }} ${{ matrix.artifact }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_iam_role }}
          aws-region: ap-northeast-1

      - name: Upload artifact
        working-directory: ${{ github.workspace }}
        run: |
          aws s3 cp ${{ matrix.artifact }} ${{ secrets.aws_s3_bucket }}

